# Site settings
title: "Mathilde Panes Resume"
#description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mathilde Panes"
resume_title:                   "Information Specialist"
resume_contact_email:           "mathilde.panes[@]protonmail.com"
resume_contact_telephone:       "+41 76 679 93 37"
resume_contact_address:         "Chemin des Bruyères 3, 1007 Lausanne"
resume_header_contact_info: "Chemin des Bruyères 3, 1007 Lausanne| homerjsimpson@youremailaddress.com"
resume_header_intro: "<p>Mathilde Panes is a librarian and a technology enthusiast. She holds a MSc in Business Administration
with a major in Information Systems management 
from the Applied University of Western Switzerland and a BSc 
of Information Science from the Geneva School of Business Administration. 
She has more than 10 years of experience in scientific and academic contexts, with a strong accent on IT. 
She has worked for the World Health Organisation on their electronic resources, as a webmaster at the University Hospital
in Geneva, and as a research assistant at the Geneva School of Business Administration. 
She then held a system librarian position at the Medical of the University Hospital Centre, in Lausanne. 
She is currently team coordinator for the EFPL Library teaching team, at the Swiss Federal Institute of Technology. 
She is very interested in new methods of collaboration, the process of knowledge sharing among peers, and 
the notions around openness.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true
resume_section_languages:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/railyards"
  resume_twitter_url:           "http://twitter.com/railyards"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mathildepanes/?locale=en_US"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
